AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Tutorial
Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EC2Restart
      Handler: restart.lambda_handler
      Runtime: python3.7
      CodeUri: src
      MemorySize: 128
      Timeout: 180
      Policies:
        - AmazonEC2FullAccess